#include "LinkedLists/DoublyLinkedList.c"
#include "LinkedLists/CircularlyLinkedList.c"
#include "Stacks/LinkedStack.c"
#include "Stacks/ArrayStack.c"
#include "Queues/LinkedQueue.c"
#include "BinaryTrees/BinaryTree.c"